### ISSUE TITLE
Integrate OpenAssetIO

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/usdOpenAssetIOResolver#15]
Integrate OpenAssetIO with the resolver plugin. This likely means having to build OpenAssetIO manually, and integrating that with CI. Initialise the python plug-in system in the constructor. Configure OpenAssetIO with a manager (BAL almost certainly)
For the moment, a requirement for this resolver is that your enclosing application be being run from a python environment, as there is no C++ manager to facilitate otherwise.

**Comment by foundrytom** [comment]
Re: manager initialization - we should to use the `OPENASSETIO_DEFAULT_CONFIG ` mechanism. The tests can then use that to setup BAL.
