### ISSUE TITLE
Define MVP workflows + BDD requirements

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/usdOpenAssetIOResolver#2]
From January meetup : 

Workflows:
A file based referential USD setup (eg: parkinglot.usd) behaves as if OpenAssetIO was not configured.
In a referential USD setup, any @entity reference@ references, subLayers, payloads that return True for isEntityReference are resolved through the manager and the resulting string is handled by USD in the same way as if OpenAssetIO was not configured and the default resolver was.
If a USD write is to a path that returns True to isEntityReference, then the preflight/resolve/register dance is performed in consideration with the ResolvesFutureEntities trait (if false, raises an exception)
managemntPolicy is queried upon initialization to avoid unnecessary manager queries and or publish attempts
Create identifier based on achor passes through input
Out of scope:
Modification time (deafult implementation of base class)
Create identifier using getRelatedReferences

Tests use libusd (iether with on-disk usd files or programmatically populated stages)

Background:
OPENASSETIO_DEFAULT_MANAGER is configured with a suitable manager
The usdOpenAssetIOResolver is configured as the primary resolver

**Comment by elliotcmorris** [comment]
Re: Modification time, we had a look through the [USD source](https://github.com/PixarAnimationStudios/USD/blob/0c7b9a95f155c221ff7df9270a39a52e3b23af8b/pxr/usd/sdf/layer.cpp#L1025) and this is pretty important to get right when we come to it, even though we're just putting a default in the first time round.

**Comment by foundrytom** [comment]
Requirements defined in https://github.com/OpenAssetIO/usdOpenAssetIOResolver/issues/8
