### ISSUE TITLE
Handle unmanaged traits via ManagementPolicy

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/usdOpenAssetIOResolver#24]
Ensure unmanaged locatableContent trait queries are always passed through to the default resolver, and that we're not calling resolve on them. Devise an efficient way to test this.

**Comment by feltech** [comment]
We should probably error, rather than pass through to the default resolve (i.e. file system), since we would know that we're dealing with an entity reference.  We are already throwing a `runtime_error`.
